name: Scheduled Newman API Tests

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run your-collection.json \
          --environment your-environment.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-results
          path: results.xml
